# Generated by Django 5.2 on 2025-05-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
